"""comprobantes de transferencia del vendedor

Reemplaza el grupo de WhatsApp «COMPROBANTES TRANSF.»: lo que el vendedor avisaba por
chat queda en una fila, con su estado y su foto.

`client_uuid` es único para que el reintento de la app offline no duplique el aviso.
`monto_clp` y `facturas` admiten vacío a propósito: un comprobante incompleto se guarda
igual, marcado, porque perder el aviso es peor que registrarlo a medias.

Revision ID: 1c0fa9f42762
Revises: 755254b96901
Create Date: 2026-08-03 19:12:32.507837
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1c0fa9f42762"
down_revision: str | None = "755254b96901"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comprobante",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("client_uuid", sa.UUID(), nullable=True),
        sa.Column("vendedor_id", sa.BigInteger(), nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=True),
        sa.Column("cliente_texto", sa.String(length=255), nullable=False),
        sa.Column("facturas", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("monto_clp", sa.Numeric(precision=12, scale=0), nullable=True),
        sa.Column("banco", sa.String(length=64), nullable=True),
        sa.Column("rut_contraparte", sa.String(length=16), nullable=True),
        sa.Column("numero_operacion", sa.String(length=32), nullable=True),
        sa.Column("fecha_transferencia", sa.Date(), nullable=True),
        sa.Column("detalle", sa.Text(), nullable=False),
        sa.Column("imagen_key", sa.String(length=255), nullable=True),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("observacion", sa.Text(), nullable=False),
        sa.Column("ingresado", sa.Boolean(), nullable=False),
        sa.Column("ingresado_por", sa.BigInteger(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('listo','falta_monto','falta_factura','falta_cliente','falta_dato','duplicado_posible','abono_parcial')",
            name="ck_comprobante_estado",
        ),
        sa.CheckConstraint(
            "monto_clp IS NULL OR monto_clp > 0", name="ck_comprobante_monto_positivo"
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["cliente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingresado_por"],
            ["usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendedor_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_uuid"),
    )
    op.create_index(op.f("ix_comprobante_cliente_id"), "comprobante", ["cliente_id"], unique=False)
    op.create_index("ix_comprobante_creado_en", "comprobante", ["creado_en"], unique=False)
    op.create_index(op.f("ix_comprobante_estado"), "comprobante", ["estado"], unique=False)
    op.create_index(
        "ix_comprobante_fecha_transferencia", "comprobante", ["fecha_transferencia"], unique=False
    )
    op.create_index(
        op.f("ix_comprobante_numero_operacion"), "comprobante", ["numero_operacion"], unique=False
    )
    op.create_index(op.f("ix_comprobante_uuid"), "comprobante", ["uuid"], unique=True)
    op.create_index(
        op.f("ix_comprobante_vendedor_id"), "comprobante", ["vendedor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comprobante_vendedor_id"), table_name="comprobante")
    op.drop_index(op.f("ix_comprobante_uuid"), table_name="comprobante")
    op.drop_index(op.f("ix_comprobante_numero_operacion"), table_name="comprobante")
    op.drop_index("ix_comprobante_fecha_transferencia", table_name="comprobante")
    op.drop_index(op.f("ix_comprobante_estado"), table_name="comprobante")
    op.drop_index("ix_comprobante_creado_en", table_name="comprobante")
    op.drop_index(op.f("ix_comprobante_cliente_id"), table_name="comprobante")
    op.drop_table("comprobante")
    # ### end Alembic commands ###
