"""conciliacion bancaria y dte

Fase 2: la cartola del banco (`movimiento_banco`) y los documentos tributarios
(`dte`), más el enlace desde `pago` al movimiento que lo respalda.

`pago.movimiento_banco_id` es único: un abono en la cuenta no puede respaldar dos
comprobantes distintos.

Revision ID: 755254b96901
Revises: f842a1b09129
Create Date: 2026-08-03 16:01:17.481690
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "755254b96901"
down_revision: str | None = "f842a1b09129"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movimiento_banco",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("id_externo", sa.String(length=128), nullable=False),
        sa.Column("proveedor", sa.String(length=32), nullable=False),
        sa.Column("cuenta", sa.String(length=64), nullable=True),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("monto_clp", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("referencia", sa.String(length=128), nullable=True),
        sa.Column("rut_contraparte", sa.String(length=16), nullable=True),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('sin_conciliar','conciliado','ignorado')", name="ck_movimiento_estado"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id_externo"),
    )
    op.create_index(
        op.f("ix_movimiento_banco_estado"), "movimiento_banco", ["estado"], unique=False
    )
    op.create_index(op.f("ix_movimiento_banco_fecha"), "movimiento_banco", ["fecha"], unique=False)
    op.create_index(
        op.f("ix_movimiento_banco_referencia"), "movimiento_banco", ["referencia"], unique=False
    )
    op.create_index(op.f("ix_movimiento_banco_uuid"), "movimiento_banco", ["uuid"], unique=True)
    op.create_index(
        "ix_movimiento_fecha_monto", "movimiento_banco", ["fecha", "monto_clp"], unique=False
    )
    op.create_table(
        "dte",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.Integer(), nullable=False),
        sa.Column("folio", sa.BigInteger(), nullable=True),
        sa.Column("pedido_id", sa.BigInteger(), nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=False),
        sa.Column("rut_receptor", sa.String(length=16), nullable=False),
        sa.Column("neto_clp", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("iva_clp", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("total_clp", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=True),
        sa.Column("glosa_sii", sa.Text(), nullable=True),
        sa.Column("xml_key", sa.String(length=255), nullable=True),
        sa.Column("pdf_key", sa.String(length=255), nullable=True),
        sa.Column("referencia_dte_id", sa.BigInteger(), nullable=True),
        sa.Column("emitido_por", sa.BigInteger(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('emitido','aceptado','rechazado','anulado')", name="ck_dte_estado"
        ),
        sa.CheckConstraint("tipo IN (33,52,61)", name="ck_dte_tipo"),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["cliente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["emitido_por"],
            ["usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedido.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referencia_dte_id"],
            ["dte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo", "folio", name="uq_dte_tipo_folio"),
    )
    op.create_index(op.f("ix_dte_cliente_id"), "dte", ["cliente_id"], unique=False)
    op.create_index(op.f("ix_dte_estado"), "dte", ["estado"], unique=False)
    op.create_index(op.f("ix_dte_folio"), "dte", ["folio"], unique=False)
    op.create_index(op.f("ix_dte_pedido_id"), "dte", ["pedido_id"], unique=False)
    op.create_index(op.f("ix_dte_tipo"), "dte", ["tipo"], unique=False)
    op.create_index(op.f("ix_dte_uuid"), "dte", ["uuid"], unique=True)
    op.add_column("pago", sa.Column("movimiento_banco_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "pago", sa.Column("conciliacion_confianza", sa.Numeric(precision=4, scale=3), nullable=True)
    )
    op.create_unique_constraint("uq_pago_movimiento_banco", "pago", ["movimiento_banco_id"])
    op.create_foreign_key(
        "fk_pago_movimiento_banco", "pago", "movimiento_banco", ["movimiento_banco_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_pago_movimiento_banco", "pago", type_="foreignkey")
    op.drop_constraint("uq_pago_movimiento_banco", "pago", type_="unique")
    op.drop_column("pago", "conciliacion_confianza")
    op.drop_column("pago", "movimiento_banco_id")
    op.drop_index(op.f("ix_dte_uuid"), table_name="dte")
    op.drop_index(op.f("ix_dte_tipo"), table_name="dte")
    op.drop_index(op.f("ix_dte_pedido_id"), table_name="dte")
    op.drop_index(op.f("ix_dte_folio"), table_name="dte")
    op.drop_index(op.f("ix_dte_estado"), table_name="dte")
    op.drop_index(op.f("ix_dte_cliente_id"), table_name="dte")
    op.drop_table("dte")
    op.drop_index("ix_movimiento_fecha_monto", table_name="movimiento_banco")
    op.drop_index(op.f("ix_movimiento_banco_uuid"), table_name="movimiento_banco")
    op.drop_index(op.f("ix_movimiento_banco_referencia"), table_name="movimiento_banco")
    op.drop_index(op.f("ix_movimiento_banco_fecha"), table_name="movimiento_banco")
    op.drop_index(op.f("ix_movimiento_banco_estado"), table_name="movimiento_banco")
    op.drop_table("movimiento_banco")
    # ### end Alembic commands ###
