"""esquema inicial: catalogo, clientes, pedidos y pagos

Revision ID: d49e04f8dc27
Revises: 
Create Date: 2026-08-03 13:26:55.080704
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd49e04f8dc27'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # La migración se basta a sí misma: infra/postgres/init sólo corre al crear el
    # cluster local, y CI levanta un Postgres limpio.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_fuente',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('edicion', sa.String(length=64), nullable=True),
    sa.Column('paginas', sa.Integer(), nullable=False),
    sa.Column('filas_detectadas', sa.Integer(), nullable=False),
    sa.Column('filas_cargables', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='uq_catalogo_fuente_sha256')
    )
    op.create_index(op.f('ix_catalogo_fuente_sha256'), 'catalogo_fuente', ['sha256'], unique=False)
    op.create_table('categoria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('rol', sa.String(length=16), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rol IN ('vendedor','cliente','bodega','admin')", name='ck_usuario_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_uuid'), 'usuario', ['uuid'], unique=True)
    op.create_table('catalogo_fila_cruda',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fuente_id', sa.BigInteger(), nullable=False),
    sa.Column('pagina', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('codigo_raw', sa.Text(), nullable=True),
    sa.Column('descripcion_raw', sa.Text(), nullable=True),
    sa.Column('venta_min_raw', sa.Text(), nullable=True),
    sa.Column('marca_raw', sa.Text(), nullable=True),
    sa.Column('medida_raw', sa.Text(), nullable=True),
    sa.Column('precio_raw', sa.Text(), nullable=True),
    sa.Column('confianza', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('problemas', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('posicion', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['catalogo_fuente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_fila_cruda_fuente_id'), 'catalogo_fila_cruda', ['fuente_id'], unique=False)
    op.create_index('ix_fila_cruda_fuente_pagina', 'catalogo_fila_cruda', ['fuente_id', 'pagina'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rut', sa.String(length=16), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nombre_fantasia', sa.String(length=255), nullable=True),
    sa.Column('giro', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('comuna', sa.String(length=128), nullable=True),
    sa.Column('ciudad', sa.String(length=128), nullable=True),
    sa.Column('email_dte', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.Column('vendedor_id', sa.BigInteger(), nullable=True),
    sa.Column('condicion_pago', sa.String(length=32), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_index(op.f('ix_cliente_uuid'), 'cliente', ['uuid'], unique=True)
    op.create_table('producto',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('categoria_id', sa.BigInteger(), nullable=True),
    sa.Column('marca', sa.String(length=128), nullable=True),
    sa.Column('medida', sa.String(length=128), nullable=True),
    sa.Column('medida_valor', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('medida_unidad', sa.String(length=16), nullable=True),
    sa.Column('unidad_venta', sa.String(length=16), nullable=False),
    sa.Column('multiplo_venta', sa.Integer(), nullable=False),
    sa.Column('envase', sa.String(length=32), nullable=True),
    sa.Column('precio_lista_clp', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('imagen_key', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('multiplo_venta >= 1', name='ck_producto_multiplo_positivo'),
    sa.CheckConstraint('precio_lista_clp >= 0', name='ck_producto_precio_no_negativo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_producto_descripcion_trgm', 'producto', ['descripcion'], unique=False, postgresql_using='gin', postgresql_ops={'descripcion': 'gin_trgm_ops'})
    op.create_index(op.f('ix_producto_uuid'), 'producto', ['uuid'], unique=True)
    op.create_table('pago',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('monto_clp', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('metodo', sa.String(length=24), nullable=False),
    sa.Column('referencia', sa.String(length=128), nullable=True),
    sa.Column('comprobante_key', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=24), nullable=False),
    sa.Column('registrado_por', sa.BigInteger(), nullable=True),
    sa.Column('verificado_por', sa.BigInteger(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('declarado','verificado','rechazado','pendiente_revision')", name='ck_pago_estado'),
    sa.CheckConstraint('monto_clp > 0', name='ck_pago_monto_positivo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['verificado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_cliente_id'), 'pago', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pago_estado'), 'pago', ['estado'], unique=False)
    op.create_index(op.f('ix_pago_uuid'), 'pago', ['uuid'], unique=True)
    op.create_table('pedido',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=24), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('vendedor_id', sa.BigInteger(), nullable=True),
    sa.Column('origen', sa.String(length=24), nullable=False),
    sa.Column('estado', sa.String(length=24), nullable=False),
    sa.Column('neto_clp', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('iva_clp', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('total_clp', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en_dispositivo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sincronizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origen IN ('app_vendedor','web_cliente','admin')", name='ck_pedido_origen'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_pedido_client_uuid'), 'pedido', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_pedido_cliente_id'), 'pedido', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedido_estado'), 'pedido', ['estado'], unique=False)
    op.create_index(op.f('ix_pedido_uuid'), 'pedido', ['uuid'], unique=True)
    op.create_table('producto_alias',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('origen', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'origen', name='uq_alias_codigo_origen')
    )
    op.create_index(op.f('ix_producto_alias_codigo'), 'producto_alias', ['codigo'], unique=False)
    op.create_index(op.f('ix_producto_alias_producto_id'), 'producto_alias', ['producto_id'], unique=False)
    op.create_table('pago_aplicacion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pago_id', sa.BigInteger(), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('monto_clp', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pago_id', 'pedido_id', name='uq_pago_pedido')
    )
    op.create_index(op.f('ix_pago_aplicacion_pago_id'), 'pago_aplicacion', ['pago_id'], unique=False)
    op.create_index(op.f('ix_pago_aplicacion_pedido_id'), 'pago_aplicacion', ['pedido_id'], unique=False)
    op.create_table('pedido_evento',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=24), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=24), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_evento_pedido_id'), 'pedido_evento', ['pedido_id'], unique=False)
    op.create_table('pedido_linea',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('multiplo_venta', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario_clp', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('total_linea_clp', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_linea_cantidad_positiva'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_linea_pedido_id'), 'pedido_linea', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_linea_pedido_id'), table_name='pedido_linea')
    op.drop_table('pedido_linea')
    op.drop_index(op.f('ix_pedido_evento_pedido_id'), table_name='pedido_evento')
    op.drop_table('pedido_evento')
    op.drop_index(op.f('ix_pago_aplicacion_pedido_id'), table_name='pago_aplicacion')
    op.drop_index(op.f('ix_pago_aplicacion_pago_id'), table_name='pago_aplicacion')
    op.drop_table('pago_aplicacion')
    op.drop_index(op.f('ix_producto_alias_producto_id'), table_name='producto_alias')
    op.drop_index(op.f('ix_producto_alias_codigo'), table_name='producto_alias')
    op.drop_table('producto_alias')
    op.drop_index(op.f('ix_pedido_uuid'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_estado'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_cliente_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_client_uuid'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_pago_uuid'), table_name='pago')
    op.drop_index(op.f('ix_pago_estado'), table_name='pago')
    op.drop_index(op.f('ix_pago_cliente_id'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_producto_uuid'), table_name='producto')
    op.drop_index('ix_producto_descripcion_trgm', table_name='producto', postgresql_using='gin', postgresql_ops={'descripcion': 'gin_trgm_ops'})
    op.drop_table('producto')
    op.drop_index(op.f('ix_cliente_uuid'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index('ix_fila_cruda_fuente_pagina', table_name='catalogo_fila_cruda')
    op.drop_index(op.f('ix_catalogo_fila_cruda_fuente_id'), table_name='catalogo_fila_cruda')
    op.drop_table('catalogo_fila_cruda')
    op.drop_index(op.f('ix_usuario_uuid'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('categoria')
    op.drop_index(op.f('ix_catalogo_fuente_sha256'), table_name='catalogo_fuente')
    op.drop_table('catalogo_fuente')
    # ### end Alembic commands ###
